export const COMMIT_IS_AUTHENTICATED = 'COMMIT_IS_AUTHENTICATED'
export const REQUEST_MY_PAGE_MEMBER_INFO = 'REQUEST_MY_PAGE_MEMBER_INFO'
export const REQUEST_MY_PAGE_MEMBER_INFO_TO_SPRING = 'REQUEST_MY_PAGE_MEMBER_INFO_TO_SPRING'
export const UPDATE_MEMBER = 'UPDATE_MEMBER'